services:
  backend:
    image: backend
    build:
      context: tech_challenge1/backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
