name: Docker Image CI
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install root dependencies
      run: npm ci --ignore-scripts
    
    - name: Install backend dependencies
      run: npm ci --ignore-scripts
      working-directory: tech_challenge1/backend
      
    - name: Rebuild native modules
      run: npm rebuild bcrypt
      working-directory: tech_challenge1/backend
    
    - name: Run linting
      run: npm run lint
      working-directory: tech_challenge1/backend
    
    - name: Run tests
      run: npm test
      working-directory: tech_challenge1/backend

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build tech_challenge1/backend --file tech_challenge1/backend/Dockerfile --tag my-image-name:$(date +%s)
